name: 서버/스레드 충돌 및 Stacktrace (한국어)
description: 서버/스레드의 충돌 또는 Stacktrace를 신고하세요.
labels: ["bug"]
assignees: ["AlphaKR93"]
body:
  - type: markdown
    attributes:
      value: |
        오류를 신고하기 전, 이 오류가 Prismarine의 **최신 버전** 에서 발생한 것이 확실한지 확인해주세요.
        또한, 이 오류가 이미 신고되어 있지 않은지 확인해주세요.

  - type: input
    id: spark
    attributes:
      label: Spark URL
      description: Spark 프로필 링크가 있다면 여기에 입력해주세요.
      placeholder: 'TIP: 프로필 링크는 서버에서 ''/spark profiler --timeout (테스트할 초, 예를 들어 300)'' 을 입력하여 얻을 수 있어요.'
    validations:
      required: false

  - type: textarea
    id: describe-error
    attributes:
      label: 오류 설명
      description: 오류에 대한 모든 정보를 서술해주세요.
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: 충돌 로그 또는 Stacktrace
      description: 충돌 로그 또는 Stacktrace "전문" 을 입력해주세요.
      placeholder: |
        hastebin 또는 로그를 여기에 입력해주세요.

        TIP: 여기를 클릭하고 파일을 드래그하면 파일을 업로드 할 수 있습니다.
        파일은 Prismarine 팀이 오류를 해결하는 데 도움을 줄 수 있습니다.
    validations:
      required: true

  - type: textarea
    id: how-to-reproduce-error
    attributes:
      label: 오류 재현 방법 (가능한 경우)
      description: 오류를 재현할 수 있는 방법을 서술해주세요.
      placeholder: |
        1. '...' 로 이동합니다.
        2. '....' 를 입력합니다.
        3. '....' 를 선택합니다.
        4. '....' 플러그인을 추가합니다.
        5. '....' 데이터팩을 추가합니다.
        6. 이렇게 하면 오류가 발생합니다.
    validations:
      required: false

  - type: textarea
    id: plugins
    attributes:
      label: 플러그인 리스트
      description: 서버에 설치되어있는 모든 플러그인의 리스트를 적어주세요.
      placeholder: |
        /plugins 를 입력하여 플러그인 리스트를 확인할 수 있어요.
        적용한 플러그인이 없을 경우 "없음" 이라고 입력해주세요!
    validations:
      required: true

  - type: textarea
    id: datapacks
    attributes:
      label: 데이터팩 리스트
      description: 서버에 설치되어있는 모든 데이터팩의 리스트를 적어주세요.
      placeholder: |
        ''/datapack list'' 를 입력하여 데이터팩 리스트를 확인할 수 있어요.
        적용한 데이터팩이 없을 경우 "없음" 이라고 입력해주세요!
    validations:
      required: true

  - type: input
    id: prismarine
    attributes:
      label: Prismarine 버전
      description: Prismarine의 버전을 입력해주세요.
      placeholder: |
        TIP: Prismarine의 버전은 ''/version'' 을 입력하여 확인할 수 있어요.
        예: git-Prismarine-"77f3c4a" (MC: 1.19.1)
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: 신고하기 전, 다시 한번 확인해주세요.
      options:
        - label: 저는 이 Minecraft 버전에서 최신 버전의 Prismarine을 사용하고 있습니다.
          required: true

        - label: 저는 이 오류가 신고되지 않았음을 확인했습니다.
          required: true

        - label: 이 버전은 Prismarine에서 지원하는 버전입니다.
          required: true
