name: 서버/스레드 충돌 및 Stacktrace (한국어)
description: 서버/스레드의 충돌 또는 Stacktrace를 신고하세요.
labels: ["bug"]
assignees: ["AlphaKR93"]
body:
  - type: markdown
    attributes:
      value: |
        오류를 신고하기 전, 이 오류가 Prismarine의 **최신 버전** 에서 발생한 것이 확실한지 확인해주세요.
        또한, 이 오류가 이미 신고되어 있지 않은지 확인해주세요.

  - type: input
    id: spark
    attributes:
      label: Spark URL
      description: Spark 프로필 링크가 있다면 여기에 입력해주세요.
      placeholder: 'TIP: 프로필 링크는 서버에서 ''/spark profiler --timeout (테스트할 초, 예를 들어 300)'' 을 입력하여 얻을 수 있어요.'
    validations:
      required: false
  - type: checkboxes
    id: checks
    attributes:
      label: 신고하기 전, 다시 한번 확인해주세요.
      options:
        - label: 저는 이 Minecraft 버전에서 최신 버전의 Prismarine을 사용하고 있습니다.
          required: true

        - label: 저는 이 오류가 신고되지 않았음을 확인했습니다.
          required: true

        - label: 이 버전은 Prismarine에서 지원하는 버전입니다.
          required: true
