name: Update Productive Gists

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
          GIST_ID: e0ba60e59d70238a13fc1fce9f3dd972
          TIMEZONE: Asia/Seoul
