name: Update Language Gists

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: "16.x"

      - name: Cache
        uses: actions/cache@main
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake pkg-config libicu-dev zlib1g-dev libcurl4-openssl-dev libssl-dev ruby-dev
          sudo gem install github-linguist
          npm install

      - name: Update gist
        run: npm start
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
          GIST_ID: d609b5675278d1e4cb47107e189b9727
          USERNAME: AlphaKR93
