name: Update Language Gists

on:
  push:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: "16.x"
      - uses: actions/cache@main
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: |
          sudo apt-get update
          sudo apt-get install cmake pkg-config libicu-dev zlib1g-dev libcurl4-openssl-dev libssl-dev ruby-dev
          sudo gem install github-linguist
          npm install
      - run: npm start
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: d609b5675278d1e4cb47107e189b9727
          USERNAME: AlphaKR93
