name: Update gist with Code::Stats stats
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Update gist
        run: python codestats_box.py
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
          GIST_ID: 822f08c2f6741d60c1ecf9063c5d841a
          CODE_STATS_USERNAME: AlphaKR93
          STATS_TYPE: recent-xp
