name: Scheduled

on:
  schedule:
    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
          GIST_ID: e0ba60e59d70238a13fc1fce9f3dd972
          TIMEZONE: Asia/Seoul
      - uses: puf17640/covid-box@master
        env:
          GH_PAT: ${{ secrets.TOKEN }}
          COUNTRY: KR
          GIST_ID: 32bac4a4e2280ec2e0aa7252ce3c7a02
