name: Scheduled

on:
  push:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
          GIST_ID: e0ba60e59d70238a13fc1fce9f3dd972
          TIMEZONE: Asia/Seoul
